name = "Todos"
language = "python"
modules = ["django"]

containerization = "docker"
srcdir = "src"
stubdir = "stubs"

[[tasks]]
name = "models"
description = "Implement two models: `Todo` and `Collection`"
runtarget = "tests/test_models.py"
injectfiles = ["main/models.py"]

[[tasks]]
name = "crud"
description = "Implement CRUD for two models: `Todo` and `Collection`"
runtarget = "tests/test_crud.py"
injectfiles = ["main/views.py"]

[[tasks]]
name = "models and crud"
description = """Implement models then implement CRUD.
                 Easy."""
injectfiles = {models = "main/models.py", crud = "main/views.py"}
